export type Tab = 
|'dashboard' 
| 'sales' 
| 'products' 
| 'orders' 
| 'order-management' 
| 'reports' 
| 'revenue-overview' 
| 'revenue-staff' 
| 'revenue-product' 
| 'customer-report' 
| 'appointment-report' 
| 'inventory-report' 
| 'settings' 
| 'self-service' 
| 'customer-view' 
| 'cashier' 
| 'customers' 
| 'users' 
| 'role-groups' 
| 'appointments' 
| 'product-categories' 
| 'categories' 
| 'brands' 
| 'stock-in' 
| 'stock-out' 
| 'inventory' 
| 'inventory-history';


